version: '3.4'

services:
    
    web:
        #image: ems-web
        image: ${DOCKER_REGISTRY:-mahmudkoli}/ems-web:${PLATFORM:-linux}-${TAG:-latest}
        #image: ${DOCKER_REGISTRY-}ems-web
        build:
          context: .
          dockerfile: EmailMarketing.Web/Dockerfile
          #network: host
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ConnectionStrings__DefaultConnection=Host=${DB_SERVER};Database=${DB_NAME};Username=${DB_USER_ID};Password=${DB_PASSWORD};Port=${DB_PORT:-5432};
          - AppSettings__ContactImportFileUrl=${ROOT_URL}/${CONTACT_IMPORT_FILE_URL}
          - AppSettings__ContactExportFileUrl=${ROOT_URL}/${CONTACT_EXPORT_FILE_URL}
          - AppSettings__EmailSenderFileUrl=${ROOT_URL}/${EMAIL_SENDER_FILE_URL}
          - AppSettings__CampaignExportFileUrl=${ROOT_URL}/${CAMPAIGN_EXPORT_FILE_URL}
        ports:
          - "8080:80"
          - "44380:443"
          #- "8080-8085:80"
          #- "44380-44385:443"
        #extra_hosts:
          #- "WIN_MSSQL:192.168.0.1"
        depends_on:
          - db
        volumes:
          - data-volume:${VOLUME_CONTAINER_DIRECTORY}
          # - C:\\MailToEMS\Web:/app/wwwroot
          
    db:
        image: "postgres:15"
        environment:
            POSTGRES_DB: ${DB_NAME:-MailtoEMS}
            POSTGRES_USER: ${DB_USER_ID:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
        ports:
          - "${DB_PORT:-5432}:5432"
        volumes:
          - postgres-data:/var/lib/postgresql/data
    
    # contact-import-worker:
    #     #image: ems-contact-import-worker
    #     image: ${DOCKER_REGISTRY:-mahmudkoli}/ems-contact-import-worker:${PLATFORM:-linux}-${TAG:-latest}
    #     #image: ${DOCKER_REGISTRY-}ems-contact-import-worker
    #     build:
    #       context: .
    #       dockerfile: EmailMarketing.ExcelWorkerService/Dockerfile
    #     environment:
    #       - ASPNETCORE_ENVIRONMENT=Production
    #       - ConnectionStrings__DefaultConnection=Host=${DB_SERVER};Database=${DB_NAME};Username=${DB_USER_ID};Password=${DB_PASSWORD};Port=${DB_PORT:-5432};
    #       - WorkerSettings__ContactImportFileUrl=${ROOT_URL}/${CONTACT_IMPORT_FILE_URL}
    #       - WorkerSettings__ContactImportLogUrl=${ROOT_URL}/${CONTACT_IMPORT_LOG_URL}
    #     #depends_on:
    #       #- db
    #     volumes:
    #       - data-volume:${VOLUME_CONTAINER_DIRECTORY}
    #       # - C:\\MailToEMS\ContactImport:/app/wwwroot
    
    # email-sender-worker:
    #     #image: ems-email-sender-worker
    #     image: ${DOCKER_REGISTRY:-mahmudkoli}/ems-email-sender-worker:${PLATFORM:-linux}-${TAG:-latest}
    #     build:
    #       context: .
    #       dockerfile: EmailMarketing.EmailSendingWorkerService/Dockerfile
    #     environment:
    #       - ASPNETCORE_ENVIRONMENT=Production
    #       - ConnectionStrings__DefaultConnection=Host=${DB_SERVER};Database=${DB_NAME};Username=${DB_USER_ID};Password=${DB_PASSWORD};Port=${DB_PORT:-5432};
    #       - WorkerSettings__EmailSenderFileUrl=${ROOT_URL}/${EMAIL_SENDER_FILE_URL}
    #       - WorkerSettings__EmailSenderLogUrl=${ROOT_URL}/${EMAIL_SENDER_LOG_URL}
    #       - WorkerSettings__EmailOpenTrackingUrl=${EMAIL_OPEN_TRACKING_URL}
    #     #depends_on:
    #       #- db
    #     volumes:
    #       - data-volume:${VOLUME_CONTAINER_DIRECTORY}
    
    # contact-export-worker:
    #     #image: ems-contact-export-worker
    #     image: ${DOCKER_REGISTRY:-mahmudkoli}/ems-contact-export-worker:${PLATFORM:-linux}-${TAG:-latest}
    #     build:
    #       context: .
    #       dockerfile: EmailMarketing.ExcelExportWorkerService/Dockerfile
    #     environment:
    #       - ASPNETCORE_ENVIRONMENT=Production
    #       - ConnectionStrings__DefaultConnection=Host=${DB_SERVER};Database=${DB_NAME};Username=${DB_USER_ID};Password=${DB_PASSWORD};Port=${DB_PORT:-5432};
    #       - WorkerSettings__ContactExportFileUrl=${ROOT_URL}/${CONTACT_EXPORT_FILE_URL}
    #       - WorkerSettings__ContactExportLogUrl=${ROOT_URL}/${CONTACT_EXPORT_LOG_URL}
    #     #depends_on:
    #       #- db
    #     volumes:
    #       - data-volume:${VOLUME_CONTAINER_DIRECTORY}
    
    # campaign-export-worker:
    #     #image: ems-campaign-export-worker
    #     image: ${DOCKER_REGISTRY:-mahmudkoli}/ems-campaign-export-worker:${PLATFORM:-linux}-${TAG:-latest}
    #     build:
    #       context: .
    #       dockerfile: EmailMarketing.CampaingReportExcelExportService/Dockerfile
    #     environment:
    #       - ASPNETCORE_ENVIRONMENT=Production
    #       - ConnectionStrings__DefaultConnection=Host=${DB_SERVER};Database=${DB_NAME};Username=${DB_USER_ID};Password=${DB_PASSWORD};Port=${DB_PORT:-5432};
    #       - WorkerSettings__CampaignExportFileUrl=${ROOT_URL}/${CAMPAIGN_EXPORT_FILE_URL}
    #       - WorkerSettings__CampaignExportLogUrl=${ROOT_URL}/${CAMPAIGN_EXPORT_LOG_URL}
    #     #depends_on:
    #       #- db
    #     volumes:
    #       - data-volume:${VOLUME_CONTAINER_DIRECTORY}
    
volumes:
    data-volume: 
        external: true
        name: ${VOLUME_NAME}
        #driver: local
        #driver_opts:
            #o: bind
            #type: none
            #device: ${VOLUME_HOST_DIRECTORY}
    postgres-data:
